version: 2

sources:
  - name: raw
    schema: greenweez_data0826_pt
    description: raw source files for greenweez finance department
    tables:
      - name: products
        identifier: raw_gz_product
        description: product list in greenweez
      - name: sales
        identifier: raw_gz_sales
        description: saled data for greenweez
      - name: ship
        identifier: raw_gz_ship
        description: shipment data for each package

